### ISSUE TITLE
Ordo Solar dosent Produce correct EU

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/Electro-Magic-Tools#1]
The Ordo Solar pannal dosent do its magic effect of x3 the out put of EU
![07891f7f6e5ebf52e17ad2706be87b4d 1](https://cloud.githubusercontent.com/assets/23045776/21580365/c1a225ec-cfa4-11e6-9b76-cab9a1e53e8c.png)
its an ability of the Ordo to do x3 power gen
all have some special effects

aswell as the triple compressed and double

**Comment by Dream-Master** [comment]
@Technus Are you able to fix it?

**Comment by Ugachaga** [comment]
Can't confirm, works fine for me. At least in creative.

**Comment by Dream-Master** [comment]
we update EMT mod and it should fixed now.
