### ISSUE TITLE
Electric Scribing tools doesn't work properly

### ISSUE THREAD

**Issue by Antifluxfield** [GTNewHorizons/Electro-Magic-Tools#2]
It is consuming duability, not electricity...

**Comment by Dream-Master** [comment]
@Antifluxfield any idea how to fix
@fewizz

**Comment by Dream-Master** [comment]
So far i see ic2 tools have only a electric bar not a durability bare like gt tools.

**Comment by bartimaeusnek** [comment]
They dont even have duability.
